name: "Build"
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Build Jacdac
        run: sh mk.sh
      - name: Build Tests
        run: dotnet build .\Jacdac.Tests\Jacdac.Tests.csproj
      - name: Run tests
        run: dotnet test .\Jacdac.Tests\Jacdac.Tests.csproj
      - name: Semantic release
        run: npx -p=@semantic-release/git -p=@semantic-release/github -p=@semantic-release/exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
